# Generated by Django 5.0.6 on 2024-06-05 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatsstory',
            old_name='user_id',
            new_name='chat_id',
        ),
    ]
