# Generated by Django 5.0.6 on 2024-06-06 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_chatsstory_answer_remove_chatsstory_question_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Context',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=255)),
                ('data', models.JSONField(default=list)),
            ],
        ),
        migrations.AlterModelOptions(
            name='chatsstory',
            options={'verbose_name_plural': 'chat histories'},
        ),
    ]
