# Generated by Django 5.0.6 on 2024-06-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_context_alter_chatsstory_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='context',
            name='customer_id',
            field=models.CharField(editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='context',
            name='data',
            field=models.JSONField(default=list, editable=False),
        ),
    ]
