# Generated by Django 5.0.6 on 2024-06-06 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_context_customer_id_alter_context_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='context',
            name='customer_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='context',
            name='data',
            field=models.JSONField(default=list),
        ),
    ]
