# Generated by Django 5.0.6 on 2024-06-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_context_customer_id_alter_context_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='context',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
