# Generated by Django 5.0.6 on 2024-06-08 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_chatsstory_chatshistory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(choices=[('GPT-3.5-turbo', 'gpt-3.5-turbo'), ('GPT-4o', 'gpt-4o'), ('GPT-4', 'gpt-4-turbo')], max_length=255, unique=True)),
                ('system_prompt', models.TextField()),
                ('number_of_chunks', models.IntegerField()),
                ('number_of_QA_history', models.IntegerField()),
            ],
        ),
    ]
