# Generated by Django 5.0.6 on 2024-06-08 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_modelsettings_options_remove_modelsettings_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelsettings',
            name='temperature',
            field=models.FloatField(default=0.5),
        ),
        migrations.AlterField(
            model_name='modelsettings',
            name='number_of_QA_history',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='modelsettings',
            name='number_of_chunks',
            field=models.IntegerField(default=5),
        ),
    ]
