# Generated by Django 5.0.6 on 2024-06-08 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_modelsettings_temperature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelsettings',
            name='model_name',
            field=models.CharField(choices=[('gpt-3.5-turbo', 'GPT-3.5-turbo'), ('gpt-4o', 'GPT-4o'), ('gpt-4-turbo', 'GPT-4')], default='gpt-3.5-turbo', max_length=255, unique=True),
        ),
    ]
